// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalmFarm.Models
{
    public partial class Cow
    {
        public Cow()
        {
            Pregnancy = new HashSet<Pregnancy>();
            Sold = new HashSet<Sold>();
        }

        public int CowId { get; set; }
        public string UId { get; set; }
        public string NickName { get; set; }
        public DateTime BirthDate { get; set; }
        public string Sex { get; set; }
        public int? Kpn { get; set; }
        public string MomUid { get; set; }
        public string Epd { get; set; }
        public string Comment { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public int FarmId { get; set; }

        public virtual Farm Farm { get; set; }
        public virtual ICollection<Pregnancy> Pregnancy { get; set; }
        public virtual ICollection<Sold> Sold { get; set; }
    }
}