// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalmFarm.Models
{
    public partial class Farm
    {
        public Farm()
        {
            Cow = new HashSet<Cow>();
        }

        public int FarmId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Cow> Cow { get; set; }
    }
}