// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PalmFarm.Models
{
    public partial class Pregnancy
    {
        public int Id { get; set; }
        public int CowId { get; set; }
        public DateTime PregnantDate { get; set; }
        public int Kpn { get; set; }
        public string PregnancyStatus { get; set; }
        public DateTime? BirthDate { get; set; }

        public virtual Cow Cow { get; set; }
    }
}